--------------------------------------------------------
--  Arquivo: DROP_LEGADOS_V1.sql
--  Autor: Antigravity/Renach-DEP
--  Data: 03/03/2026
--  Descrição: Script de limpeza definitiva
--  INSTRUÇÃO: Faça UPLOAD em SQL Scripts e clique em "Run".
--------------------------------------------------------

DROP PACKAGE PKG_RENACH_DEP;
DROP VIEW VW_RNCH_RELATORIO_CONSOLIDADO;

-- Tabelas RENACH_DEP_TB
DROP TABLE RENACH_DEP_TB_AUD_APROVADO CASCADE CONSTRAINTS;
DROP TABLE RENACH_DEP_TB_AUD_BLOQUEADO CASCADE CONSTRAINTS;
DROP TABLE RENACH_DEP_TB_AUD_LOG CASCADE CONSTRAINTS;
DROP TABLE RENACH_DEP_TB_ETL_FINAL CASCADE CONSTRAINTS;
DROP TABLE RENACH_DEP_TB_RET_SERPRO CASCADE CONSTRAINTS;
DROP TABLE RENACH_DEP_TB_STG_FORM_CAD CASCADE CONSTRAINTS;
DROP TABLE RENACH_DEP_TB_STG_REL_CURSO CASCADE CONSTRAINTS;
DROP TABLE RENACH_DEP_TB_STG_RET_SERPRO CASCADE CONSTRAINTS;
DROP TABLE RENACH_DEP_TB_USUARIO CASCADE CONSTRAINTS;

-- Tabelas RNCH_DEP_TB
DROP TABLE RNCH_DEP_TB_AUD_APROVADO CASCADE CONSTRAINTS;
DROP TABLE RNCH_DEP_TB_AUD_BLOQUEADO CASCADE CONSTRAINTS;
DROP TABLE RNCH_DEP_TB_AUD_LOG CASCADE CONSTRAINTS;
DROP TABLE RNCH_DEP_TB_ETL_FINAL CASCADE CONSTRAINTS;
DROP TABLE RNCH_DEP_TB_SERPRO CASCADE CONSTRAINTS;
DROP TABLE RNCH_DEP_TB_STG_FORM_CAD CASCADE CONSTRAINTS;
DROP TABLE RNCH_DEP_TB_STG_REL_CURSO CASCADE CONSTRAINTS;
DROP TABLE RNCH_DEP_TB_STG_SERPRO CASCADE CONSTRAINTS;
